<?php
/**
 * Curbside pickup for Magento 2
 *
 * This module extends the base pick up in-store Magento 2 functionality
 * adding an option for a curbside pick up
 *
 * @package ImaginationMedia\CurbsidePickup
 * @author Antonio Lolić <antonio@imaginationmedia.com>
 * @copyright Copyright (c) 2020 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Magento\Sales\Block\Order\History $block */

use ImaginationMedia\CurbsidePickup\ViewModel\OrderHistory;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */

$_orders = $block->getOrders();

/** @var OrderHistory $curbsideViewModel */
$curbsideViewModel = $block->getData('curbsideViewModel');

$_curbsideOrders = $curbsideViewModel->filterCurbsideOrders($_orders);
?>
<?= $block->getChildHtml('info') ?>
<?php if ($_curbsideOrders && count($_curbsideOrders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $escaper->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Delivery Date')) ?></th>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Pickup Store')) ?></th>
                    <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $escaper->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $escaper->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                <?php    /** @var Magento\Sales\Model\Order $_order */
                        $curbsideData = $curbsideViewModel->getCurbsideData($_order); ?>
                    <tr>
                        <td data-th="<?= $escaper->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Delivery Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Pickup Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $escaper->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $escaper->escapeUrl($curbsideViewModel->getViewPageUrl($_order)) ?>" class="action view">
                                <span><?= $escaper->escapeHtml(__('View Order')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
