<?php
/**
 * Curbside pickup for Magento 2
 *
 * This module extends the base pick up in-store Magento 2 functionality
 * adding an option for a curbside pick up
 *
 * @package ImaginationMedia\CurbsidePickup
 * @author Antonio Lolić <antonio@imaginationmedia.com>
 * @copyright Copyright (c) 2020 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

/** @var \Magento\Sales\Block\Order\View $block */

use ImaginationMedia\CurbsidePickup\Helper\Data;
use ImaginationMedia\CurbsidePickup\ViewModel\OrderView;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */

$deliveryTime = $block->formatDate($block->getOrder()->getCurbsideDeliveryTime(), \IntlDateFormatter::LONG, true);

/** @var OrderView $curbsideViewModel */
$curbsideViewModel = $block->getData('curbsideViewModel');

$isPickupScheduledForStore = $this->helper(Data::class)->isScheduledPickupEnabled($curbsideViewModel->getStore());
?>

<div class="order-date">
    <?= $escaper->escapeHtml(
        __(
            '<span class="label">Order Date:</span> %1',
            '<span>' . $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) . '</span>'
        ),
        ['span']
    )?>
</div>

<div class="curbside-order-delivery-date">
    <?= $escaper->escapeHtml(
        __(
            '<span class="label">Delivery Date:</span> %1',
            '<span>' . $deliveryTime . '</span>'
        ),
        ['span']
    )?>
</div>

<div class="actions-toolbar order-curbside-pickup">
    <div class="primary">
        <a class="action back" href="<?= $escaper->escapeUrl($curbsideViewModel->getPickupViewUrl()) ?>">
            <span><?= $escaper->escapeHtml(__('Curbside Pick Up Schedule Info')) ?></span>
        </a>
    </div>
</div>

