<?php

/**
 * Curbside pickup for Magento 2
 *
 * This module extends the base pick up in-store Magento 2 functionality
 * adding an option for a curbside pick up
 *
 * @package ImaginationMedia\CurbsidePickup
 * @author Antonio Lolić <antonio@imaginationmedia.com>
 * @copyright Copyright (c) 2020 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */

/** @var \Magento\Framework\View\Element\Template  $block */

/** @var \ImaginationMedia\CurbsidePickup\ViewModel\Adminhtml\OrderInfo $viewmodel */
$viewmodel = $block->getData('viewModel');

/** @var Magento\Sales\Model\Order $order */
$order = $viewmodel->getOrder();

$deliveryTime = $block->formatDate($order->getCurbsideDeliveryTime(), \IntlDateFormatter::MEDIUM, true);

if ($viewmodel->isCurbsideOrderViewPage()):
// @codingStandardsIgnoreFile
?>

    <script type="text/x-magento-init">
        {
            "*": {
                "curbsideOrderInfo": {
                    "curbsideOrderInfoHtml": <?= /* @noEscape */ $viewmodel->getOrderInfoJson() ?>
                }
            }
        }
    </script>

<?php endif; ?>
