<?php

/**
 * Curbside pickup for Magento 2
 *
 * This module extends the base pick up in-store Magento 2 functionality
 * adding an option for a curbside pick up
 *
 * @package ImaginationMedia\CurbsidePickup
 * @author Antonio Lolić <antonio@imaginationmedia.com>
 * @copyright Copyright (c) 2020 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */

/** @var \Magento\Framework\View\Element\Template  $block */

/** @var Magento\Sales\Model\Order $order */
$order = $block->getOrder();

$deliveryTime = $block->formatDate($order->getCurbsideDeliveryTime(), \IntlDateFormatter::MEDIUM, true);
?>

<tr>
    <th><?= $escaper->escapeHtml(__('Curbside Delivery Time')) ?></th>
    <td><?= $escaper->escapeHtml($deliveryTime) ?></td>
</tr>
<tr>
    <th><?= $escaper->escapeHtml(__('Curbside Order Status')) ?></th>
    <td><?= $escaper->escapeHtml($order->getStatusLabel()) ?></td>
</tr>
