<?php

/**
 * Curbside pickup for Magento 2
 *
 * This module extends the base pick up in-store Magento 2 functionality
 * adding an option for a curbside pick up
 *
 * @package ImaginationMedia\CurbsidePickup
 * @author Antonio Lolić <antonio@imaginationmedia.com>
 * @copyright Copyright (c) 2020 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */

/** @var \Magento\Framework\View\Element\Template  $block */

/** @var \ImaginationMedia\CurbsidePickup\ViewModel\Adminhtml\OrderModal $viewmodel */
$viewmodel = $block->getData('viewModel');

/** @var Magento\Sales\Model\Order $order */
$order = $viewmodel->getOrder();

$deliveryTime = $block->formatDate($order->getCurbsideDeliveryTime(), \IntlDateFormatter::MEDIUM, true);
?>

<div class="curbside_order_summary">
    <h1><?= $escaper->escapeHtml(__('Order #%1 Details', $order->getRealOrderId())) ?></h1>

    <div class="curbside_order_info">
        <table class="admin__table-secondary order-information-table">
            <tr>
                <th><?= $escaper->escapeHtml(__('Order Date:')) ?></th>
                <td><?= $escaper->escapeHtml($order->getCreatedAtFormatted(\IntlDateFormatter::MEDIUM)) ?></td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Delivery Time:')) ?></th>
                <td><?= $escaper->escapeHtml($deliveryTime) ?></td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__(' Order Status:')) ?></th>
                <td><?= $escaper->escapeHtml($order->getStatusLabel()) ?></td>
            </tr>
            <tr>
                <th><?= $escaper->escapeHtml(__('Paid Amount:')) ?></th>
                <td><?= $escaper->escapeHtml($viewmodel->getAmountPaid()) ?></td>
            </tr>
        </table>
    </div>

    <div class="curbside_order_items">
        <?= $block->getChildHtml('order_items') ?>
    </div>

    <div class="curbside_order_totals">
        <?= $block->getChildHtml('order_totals') ?>
    </div>

    <div class="curbside_order_payment">
        <?= $block->getChildHtml('order_payment') ?>
    </div>
</div>

